-- Magnitude Analysis
-- Find the total number of customers by country 
SELECT
	country,
	COUNT(customer_key) total_customers
FROM gold.dim_customers
GROUP BY country
ORDER BY total_customers DESC

-- Find total customers by gender
SELECT
	gender,
	COUNT(customer_key) total_customers
FROM gold.dim_customers
GROUP BY gender
ORDER BY total_customers DESC

-- Find total number of products by category
SELECT
	category,
	COUNT(product_key) total_products
FROM gold.dim_products
GROUP BY category
ORDER BY total_products DESC

-- What is the average cost in every category
SELECT
	category,
	AVG(cost) average_cost
FROM gold.dim_products
GROUP BY category
ORDER BY average_cost DESC

-- What is the total revenue generated for each category

SELECT
	p.category,
	SUM(s.sales_anmount) total_sales
FROM gold.fact_sales s
LEFT JOIN gold.dim_products p
ON s.product_key = p.product_key
GROUP BY p.category
ORDER BY total_sales DESC

-- Find total revenue generated by each customer
SELECT
	SUM(s.sales_anmount) total_sales,
	c.first_name,
	c.last_name,
	c.customer_key
FROM gold.fact_sales s
LEFT JOIN gold.dim_customers c
ON s.customer_key = c.customer_key
GROUP BY 
	c.first_name,
	c.last_name,
	c.customer_key

-- What is the distribution of sold items across the countries

SELECT
	c.country,
	SUM(s.quantity) Total_quantity
FROM gold.fact_sales s
LEFT JOIN gold.dim_products p
ON s.product_key = p.product_key
LEFT JOIN gold.dim_customers c
ON s.customer_key = c.customer_key
GROUP BY
	c.country
ORDER BY total_quantity DESC
